name = "SuperDataStructures"
uuid = "4910b7fa-45a4-cf47-6670-77fabb527574"
version = "1.0.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
