Base.:(==)(x::Py, y::Py) = pyeq(Bool, x, y)
Base.:(!=)(x::Py, y::Py) = pyne(Bool, x, y)
Base.:(<=)(x::Py, y::Py) = pyle(Bool, x, y)
Base.:(< )(x::Py, y::Py) = pylt(Bool, x, y)
Base.:(>=)(x::Py, y::Py) = pyge(Bool, x, y)
Base.:(> )(x::Py, y::Py) = pygt(Bool, x, y)

Base.:(==)(x::Py, y::Number) = pyeq(Bool, x, y)
Base.:(!=)(x::Py, y::Number) = pyne(Bool, x, y)
Base.:(<=)(x::Py, y::Number) = pyle(Bool, x, y)
Base.:(< )(x::Py, y::Number) = pylt(Bool, x, y)
Base.:(>=)(x::Py, y::Number) = pyge(Bool, x, y)
Base.:(> )(x::Py, y::Number) = pygt(Bool, x, y)

Base.:(==)(x::Number, y::Py) = pyeq(Bool, x, y)
Base.:(!=)(x::Number, y::Py) = pyne(Bool, x, y)
Base.:(<=)(x::Number, y::Py) = pyle(Bool, x, y)
Base.:(< )(x::Number, y::Py) = pylt(Bool, x, y)
Base.:(>=)(x::Number, y::Py) = pyge(Bool, x, y)
Base.:(> )(x::Number, y::Py) = pygt(Bool, x, y)
